from pyserini.prebuilt_index_info import IMPACT_INDEX_INFO, TF_INDEX_INFO

INDICES = {
    "bm25": {
        "dl19": "msmarco-v1-passage",
        "dl20": "msmarco-v1-passage",
        "dl21": "msmarco-v2-passage",
        "dl22": "msmarco-v2-passage",
        "dl23": "msmarco-v2-passage",
        "covid": "beir-v1.0.0-trec-covid.flat",
        "bioasq": "beir-v1.0.0-bioasq.flat",
        "nfc": "beir-v1.0.0-nfcorpus.flat",
        "nq": "beir-v1.0.0-nq.flat",
        "hotpotqa": "beir-v1.0.0-hotpotqa.flat",
        "fiqa": "beir-v1.0.0-fiqa.flat",
        "signal": "beir-v1.0.0-signal1m.flat",
        "news": "beir-v1.0.0-trec-news.flat",
        "robust04": "beir-v1.0.0-robust04.flat",
        "arguana": "beir-v1.0.0-arguana.flat",
        "touche": "beir-v1.0.0-webis-touche2020.flat",
        "cqadupstack-android": "beir-v1.0.0-cqadupstack-android.flat",
        "cqadupstack-english": "beir-v1.0.0-cqadupstack-english.flat",
        "cqadupstack-gaming": "beir-v1.0.0-cqadupstack-gaming.flat",
        "cqadupstack-gis": "beir-v1.0.0-cqadupstack-gis.flat",
        "cqadupstack-mathematica": "beir-v1.0.0-cqadupstack-mathematica.flat",
        "cqadupstack-physics": "beir-v1.0.0-cqadupstack-physics.flat",
        "cqadupstack-programmers": "beir-v1.0.0-cqadupstack-programmers.flat",
        "cqadupstack-stats": "beir-v1.0.0-cqadupstack-stats.flat",
        "cqadupstack-tex": "beir-v1.0.0-cqadupstack-tex.flat",
        "cqadupstack-unix": "beir-v1.0.0-cqadupstack-unix.flat",
        "cqadupstack-webmasters": "beir-v1.0.0-cqadupstack-webmasters.flat",
        "cqadupstack-wordpress": "beir-v1.0.0-cqadupstack-wordpress.flat",
        "quora": "beir-v1.0.0-quora.flat",
        "dbpedia": "beir-v1.0.0-dbpedia-entity.flat",
        "scidocs": "beir-v1.0.0-scidocs.flat",
        "fever": "beir-v1.0.0-fever.flat",
        "climate-fever": "beir-v1.0.0-climate-fever.flat",
        "scifact": "beir-v1.0.0-scifact.flat",
        "mrtydi-ar": "mrtydi-v1.1-arabic",
        "mrtydi-bn": "mrtydi-v1.1-bengali",
        "mrtydi-en": "mrtydi-v1.1-english",
        "mrtydi-fi": "mrtydi-v1.1-finnish",
        "mrtydi-id": "mrtydi-v1.1-indonesian",
        "mrtydi-ja": "mrtydi-v1.1-japanese",
        "mrtydi-ko": "mrtydi-v1.1-korean",
        "mrtydi-ru": "mrtydi-v1.1-russian",
        "mrtydi-sw": "mrtydi-v1.1-swahili",
        "mrtydi-te": "mrtydi-v1.1-telugu",
        "mrtydi-th": "mrtydi-v1.1-thai",
    },
    "SPLADE++_EnsembleDistil_ONNX": {
        "dl19": "msmarco-v1-passage.splade-pp-ed-text",
        "dl20": "msmarco-v1-passage.splade-pp-ed-text",
        "dl21": "",
        "dl22": "",
        "dl23": "",
        "covid": "beir-v1.0.0-trec-covid.splade-pp-ed",
        "bioasq": "beir-v1.0.0-bioasq.splade-pp-ed",
        "nfc": "beir-v1.0.0-nfcorpus.splade-pp-ed",
        "nq": "beir-v1.0.0-nq.splade-pp-ed",
        "hotpotqa": "beir-v1.0.0-hotpotqa.splade-pp-ed",
        "fiqa": "beir-v1.0.0-fiqa.splade-pp-ed",
        "signal": "beir-v1.0.0-signal1m.splade-pp-ed",
        "news": "beir-v1.0.0-trec-news.splade-pp-ed",
        "robust04": "beir-v1.0.0-robust04.splade-pp-ed",
        "arguana": "beir-v1.0.0-arguana.splade-pp-ed",
        "touche": "beir-v1.0.0-webis-touche2020.splade-pp-ed",
        "cqadupstack-android": "beir-v1.0.0-cqadupstack-android.splade-pp-ed",
        "cqadupstack-english": "beir-v1.0.0-cqadupstack-english.splade-pp-ed",
        "cqadupstack-gaming": "beir-v1.0.0-cqadupstack-gaming.splade-pp-ed",
        "cqadupstack-gis": "beir-v1.0.0-cqadupstack-gis.splade-pp-ed",
        "cqadupstack-mathematica": "beir-v1.0.0-cqadupstack-mathematica.splade-pp-ed",
        "cqadupstack-physics": "beir-v1.0.0-cqadupstack-physics.splade-pp-ed",
        "cqadupstack-programmers": "beir-v1.0.0-cqadupstack-programmers.splade-pp-ed",
        "cqadupstack-stats": "beir-v1.0.0-cqadupstack-stats.splade-pp-ed",
        "cqadupstack-tex": "beir-v1.0.0-cqadupstack-tex.splade-pp-ed",
        "cqadupstack-unix": "beir-v1.0.0-cqadupstack-unix.splade-pp-ed",
        "cqadupstack-webmasters": "beir-v1.0.0-cqadupstack-webmasters.splade-pp-ed",
        "cqadupstack-wordpress": "beir-v1.0.0-cqadupstack-wordpress.splade-pp-ed",
        "quora": "beir-v1.0.0-quora.splade-pp-ed",
        "dbpedia": "beir-v1.0.0-dbpedia-entity.splade-pp-ed",
        "scidocs": "beir-v1.0.0-scidocs.splade-pp-ed",
        "fever": "beir-v1.0.0-fever.splade-pp-ed",
        "climate-fever": "beir-v1.0.0-climate-fever.splade-pp-ed",
        "scifact": "beir-v1.0.0-scifact.splade-pp-ed",
    },
    "distilbert_tas_b": {
        "dl19": "msmarco-v1-passage.distilbert-dot-tas_b-b256",
        "dl20": "msmarco-v1-passage.distilbert-dot-tas_b-b256",
        "dl21": "",
        "dl22": "",
        "dl23": "",
        "covid": "",
        "arguana": "",
        "touche": "",
        "news": "",
        "scifact": "",
        "fiqa": "",
        "scidocs": "",
        "nfc": "",
        "quora": "",
        "dbpedia": "",
        "fever": "",
        "robust04": "",
        "signal": "",
    },
    "openai-ada2": {
        "dl19": "msmarco-v1-passage.openai-ada2",
        "dl20": "msmarco-v1-passage.openai-ada2",
        "dl21": "",
        "dl22": "",
        "dl23": "",
        "covid": "",
        "arguana": "",
        "touche": "",
        "news": "",
        "scifact": "",
        "fiqa": "",
        "scidocs": "",
        "nfc": "",
        "quora": "",
        "dbpedia": "",
        "fever": "",
        "robust04": "",
        "signal": "",
    },
}

# Extend bm25 with any prebuilt index from pyserini (module runs once on import, so INDICES is always this version)
for index_name in TF_INDEX_INFO:
    INDICES["bm25"][index_name] = index_name

for index_name in IMPACT_INDEX_INFO:
    if "splade-pp-ed" in index_name:
        INDICES["SPLADE++_EnsembleDistil_ONNX"][index_name] = index_name
